# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "Fadi" ]
  pull_request:
    branches: [ "Fadi" ]




jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v4 
    - run: npm ci
    - run: npm test


# name: Node.js CI

# on:
#   push:
#     branches: [ "Fadi" ]
#     paths:
#       - 'frontend/**'
#       - '.github/workflows/node.js.yaml'
#   pull_request:
#     branches: [ "Fadi" ]
#     paths:
#       - 'frontend/**'
#       - '.github/workflows/node.js.yaml'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [18.x, 20.x, 22.x]


#   defaults:
#       run:
#         working-directory: frontend

#   steps:
#      - uses: actions/checkout@v4
#      - run: npm ci
#      - run: npm test
